[package]
name = "app"
version = "0.1.0"
authors = ["Matt Wilson <mattjwilson@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.1"
json = "0.12.4"
